### ISSUE TITLE
Please remove JourneyMap jars from your repository

### ISSUE THREAD

**Issue by techbrew-mc** [KOT32500/Mods#2]
Hi,

JourneyMap may not be altered, file-hosted, or distributed without express written permission. Modpack usage is limited to these terms: https://journeymap.info/Modpack_FAQ

Please remove JourneyMap jars from all branches in your repository, including this one: 

https://github.com/KOT32500/Mods/blob/e3a18d7a2d187d871b3f82b6e995ca584751b0f1/journeymap-1.12.2-5.5.6.jar

Thank you!

**Comment by KOT32500** [comment]
Just now I saw your message. Sorry for such a long wait. Ok, already deleted from all repositories. Have a nice day
